In [3]:
import pandas as pd
import numpy as np
df=pd.read_csv(r"C:\Users\geeth\OneDrive\Desktop\Data analysis\student_data.csv")
print(df)


   Student_ID  Math  Science  English  Attendance
0         101    78       85       88          95
1         102    65       70       72          80
2         103    90       92       85          98
3         104    55       60       58          60
4         105    85       87       90          92
5         106    45       50       48          50
6         107    95       96       94          99
7         108    70       75       78          85
8         109    82       84       86          93
9         110    60       62       65          75


In [4]:
arr=df.to_numpy()
print(arr)

[[101  78  85  88  95]
 [102  65  70  72  80]
 [103  90  92  85  98]
 [104  55  60  58  60]
 [105  85  87  90  92]
 [106  45  50  48  50]
 [107  95  96  94  99]
 [108  70  75  78  85]
 [109  82  84  86  93]
 [110  60  62  65  75]]


In [7]:
print(np.mean(arr[:,1]))

72.5


In [8]:
std_val=np.std(arr[:,4])
print(std_val)

15.811704525445698


In [9]:
median_val=np.median(arr[:,2])
print(median_val)

79.5


In [10]:
filtered_val=[]
for i in arr:
    if i[1]>90 or i[2]>90 or i[3]>90:
        filtered_val.append(True)
    else:
        filtered_val.append(False)
print(filtered_val)
print("==================================")
newarr=arr[filtered_val]
print(newarr)

[False, False, True, False, False, False, True, False, False, False]
[[103  90  92  85  98]
 [107  95  96  94  99]]


In [13]:
filtered_val=[]
for i in arr:
    if i[4]<75:
        filtered_val.append(True)
    else:
        filtered_val.append(False)
print(filtered_val)
print("==================================")
newarr=arr[filtered_val]
print(newarr)

[False, False, False, True, False, True, False, False, False, False]
[[104  55  60  58  60]
 [106  45  50  48  50]]


In [15]:
avg_math=np.mean(arr[:,1])
avg_sci=np.mean(arr[:,2])
avg_eng=np.mean(arr[:,3])
filtered_val=[]
for i in arr:
    if i[1]>avg_math and i[2]>avg_sci and i[3]>avg_eng:
        filtered_val.append(True)
    else:
        filtered_val.append(False)
print(filtered_val)
print("==================================")
newarr=arr[filtered_val]
print(newarr)

[True, False, True, False, True, False, True, False, True, False]
[[101  78  85  88  95]
 [103  90  92  85  98]
 [105  85  87  90  92]
 [107  95  96  94  99]
 [109  82  84  86  93]]


In [16]:
total=arr[:,1]+arr[:,2]+arr[:,3]
print(total)

[251 207 267 173 262 143 285 223 252 187]


In [17]:
high=total[0]
student=arr[0,0]
for i in range(len(total)):
    if total[i]>high:
        high=total[i]
        student=arr[i,0]
print("Student:",student)
print("highest total:",high)

Student: 107
highest total: 285


In [19]:
print(np.mean(total))

225.0


In [20]:
sorted_df=df.sort_values("English",ascending=False)
print(sorted_df)

   Student_ID  Math  Science  English  Attendance
6         107    95       96       94          99
4         105    85       87       90          92
0         101    78       85       88          95
8         109    82       84       86          93
2         103    90       92       85          98
7         108    70       75       78          85
1         102    65       70       72          80
9         110    60       62       65          75
3         104    55       60       58          60
5         106    45       50       48          50


In [21]:
df["Total"]=total
top3=df.sort_values("Total",ascending=False).head(3)
print(top3)

   Student_ID  Math  Science  English  Attendance  Total
6         107    95       96       94          99    285
2         103    90       92       85          98    267
4         105    85       87       90          92    262


In [23]:
filtered_val=[]
for i in arr:
    if i[1]>=50 and i[2]>=50 and i[3]>=50 and i[4]>=75:
        filtered_val.append("Pass")
    else:
        filtered_val.append("Fail")
print(filtered_val)

df["Pass/Fail"]=filtered_val
print(df)

['Pass', 'Pass', 'Pass', 'Fail', 'Pass', 'Fail', 'Pass', 'Pass', 'Pass', 'Pass']
   Student_ID  Math  Science  English  Attendance  Total Pass/Fail
0         101    78       85       88          95    251      Pass
1         102    65       70       72          80    207      Pass
2         103    90       92       85          98    267      Pass
3         104    55       60       58          60    173      Fail
4         105    85       87       90          92    262      Pass
5         106    45       50       48          50    143      Fail
6         107    95       96       94          99    285      Pass
7         108    70       75       78          85    223      Pass
8         109    82       84       86          93    252      Pass
9         110    60       62       65          75    187      Pass


In [25]:
percent=(total/300)*100
print(percent)
df["Percentage"]=percent
print(df)

[83.66666667 69.         89.         57.66666667 87.33333333 47.66666667
 95.         74.33333333 84.         62.33333333]
   Student_ID  Math  Science  English  Attendance  Total Pass/Fail  Percentage
0         101    78       85       88          95    251      Pass   83.666667
1         102    65       70       72          80    207      Pass   69.000000
2         103    90       92       85          98    267      Pass   89.000000
3         104    55       60       58          60    173      Fail   57.666667
4         105    85       87       90          92    262      Pass   87.333333
5         106    45       50       48          50    143      Fail   47.666667
6         107    95       96       94          99    285      Pass   95.000000
7         108    70       75       78          85    223      Pass   74.333333
8         109    82       84       86          93    252      Pass   84.000000
9         110    60       62       65          75    187      Pass   62.333333


In [26]:
grade=[]
for i in percent:
    if i>=85:
        grade.append("A")
    elif i>=70:
        grade.append("B")
    elif i>=50:
        grade.append("C")
    else:
        grade.append("F")
print(grade)
df["Grade"]=grade
print(df)

['B', 'C', 'A', 'C', 'A', 'F', 'A', 'B', 'B', 'C']
   Student_ID  Math  Science  English  Attendance  Total Pass/Fail  \
0         101    78       85       88          95    251      Pass   
1         102    65       70       72          80    207      Pass   
2         103    90       92       85          98    267      Pass   
3         104    55       60       58          60    173      Fail   
4         105    85       87       90          92    262      Pass   
5         106    45       50       48          50    143      Fail   
6         107    95       96       94          99    285      Pass   
7         108    70       75       78          85    223      Pass   
8         109    82       84       86          93    252      Pass   
9         110    60       62       65          75    187      Pass   

   Percentage Grade  
0   83.666667     B  
1   69.000000     C  
2   89.000000     A  
3   57.666667     C  
4   87.333333     A  
5   47.666667     F  
6   95.000000     A  
7 